### ISSUE TITLE
issues with Cura 3.6

### ISSUE THREAD

**Issue by ElusiveTo** [nallath/CuraOrientationPlugin#10]
Seems like it dosen't work anymore with Cura 3.6, may i expect a compatible version please?

**Comment by nallath** [comment]
I've just tested it with 3.6 to make sure, but it seems to work just fine. What is the issue you're having exactly?

**Comment by ElusiveTo** [comment]
thanks for awnsering.
I put the "CuraOrientationPlugin-master" folder (extracted) in my Cura "plugins" folder.
And then run Cura, it doen't appear in extension menu.
though it was a compatibility problem.

**Comment by blargoflatsome** [comment]
Having the same problem

**Comment by nallath** [comment]
Why not just download it by means of the marketplace? It's there and then you can also get updates when they are available.

**Comment by ElusiveTo** [comment]
nothing much to say. Didn't even know the marketplace existed.
Thank you for solving the problem and making good content for cura.
May the force be with you Nallath!

**Comment by Jakobud** [comment]
This isn't working for me in 3.6 either. I installed it via Marketplace too. I select my object. Then choose either of the orientation menu options (fast or optimal). I see a small window at the bottom saying "Calculating..." or something. Then nothing happens. The object is still sitting in the middle in the same orientation I imported it at. Not sure what I could be doing wrong.

**Comment by nallath** [comment]
Could you share the logs and or the model that has the issue? If I can't reproduce the issue, there is little I can do to resolve it.

**Comment by Jakobud** [comment]
I've found it to work with some models but not this one I have. I will post a link to it.

**Comment by nallath** [comment]
Could you post the link? I'm curious as to why this is happening. Do note that I "just" wrote a connector to link the orientation alogrithm with Cura. So there might be nothing I can do to fix the issue.

**Comment by Jakobud** [comment]
Here is the STL: https://file.io/GZcLID

**Comment by Jakobud** [comment]
One thing I just realized is that perhaps the reason the plugin "is not working" for me is because the model was already sitting in the best orientation. I just tried rotating the model to an arbitrary position and then ran the plugin commands and sure enough, it rotated it back to the original position. So I guess that it was working fine all along. It just didn't appear to be. Perhaps a feature to add to your plugin would be to show a message to indicate if a model is already in the most optimized orientation.

Cool plugin. Thanks!!

**Comment by nallath** [comment]
I've added a bit more clarification to the plugin in 5c625ebabe9e476b7d94cb01bbfbbcfb765e80d0

**Comment by nallath** [comment]
Also; if you don't want to wait for it to be released on the marketplace (which should only take a day or so) you can get the pre-release on https://github.com/nallath/CuraOrientationPlugin/releases/tag/V3.2.1 (you need the 6.0.0 version if you are using Cura 4.0, the 5.0 version if you are using 3.5 or 3.6)
