### ISSUE TITLE
Auto-auto orientation?

### ISSUE THREAD

**Issue by MagnusThome** [nallath/CuraOrientationPlugin#12]
Is it possible to get the auto orientation to run automatically when a new item is opened in cura?

I had some problems googling this hehe, auto auto mode...

**Comment by nallath** [comment]
This could theoretically be possible, but there are some issues that would need solving;
- A place to toggle this behavior needs to be created
- A place to toggle which of the two needs to be done (eg fast or extended)

But it's a good suggestion. I'll have a look at it tonight after work.

**Comment by MagnusThome** [comment]
Nice!!!

**Comment by nallath** [comment]
I've had to time to implement this. It's just a regular checkbox, so it always uses the extended version of the algorithm. 

It's waiting for review right now, after that it can be downloaded via the marketplace. If you don't want to wait for that, you test it out by downloading the right version from https://github.com/nallath/CuraOrientationPlugin/releases/tag/V3.2.1 (you need the 6.0.0 version if you are using cura 4.0, the 5.0 version if you are using 3.5 or 3.6)

**Comment by MagnusThome** [comment]
Fantastic, thank you. I'll enjoy this functionality every day. :-)
