### ISSUE TITLE
Plugin disabled in Cura 4.4

### ISSUE THREAD

**Issue by szh** [nallath/CuraOrientationPlugin#14]
I just updated to Cura 4.4 (Windows 64-bit) and this plugin disappeared from the "Extensions" menu, and is grayed out in the Marketplace window:
![image](https://user-images.githubusercontent.com/546965/69273702-de48a180-0ba6-11ea-9477-7a5bcbce8599.png)
I can check the checkbox and restart Cura but it does nothing.

**Comment by nallath** [comment]
I totally forgot to do the update that was required. It should be fixed now.
