### ISSUE TITLE
Cannot find this plugin on the marketplace

### ISSUE THREAD

**Issue by fabianoriccardi** [nallath/CuraOrientationPlugin#20]
I have just upgrade to Cura 5 but I don't find nor I can't reinstall this plugin from the marketplace.

I have also searched on <https://marketplace.ultimaker.com/app/cura/plugins>, but nothing...

**Comment by nallath** [comment]
It's pending review from my colleagues. You can also get the release from the releases page: https://github.com/nallath/CuraOrientationPlugin/releases
