### ISSUE TITLE
Shortcut in Rotation tool

### ISSUE THREAD

**Issue by BagelOrb** [nallath/CuraOrientationPlugin#7]
Please make a shortcut in the rotation tool menu, so that you automatically bump into it when you are busy rotating the part yourself.

Also: when is this going to be shipped with Cura?

**Comment by nallath** [comment]
1. Thought about it, but it's impossible with current architecture. The rotate tool it it's own plugin, which I can't modify by means of this plugin. 
2. No idea. Ask Mark.
