### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by BagelOrb** [nallath/CuraOrientationPlugin#8]
The algorithm is not stable. Hitting calculate optimal angle will reposition the model in a different orientation.

Also the starting angle will affect the resulting orientation.

I'm not talking about angle around the Z axis; the model can actually get different orientations around the X and Y axis.

http://www.thingiverse.com/thing:1906284/#files

**Comment by nallath** [comment]
I've not had the same issue. All objects I tried this with seem to consistently get the same result.

**Comment by BagelOrb** [comment]
Try the object I linked to. The Stanford dragon from thingiverse

**Comment by nallath** [comment]
Issues with the algoritm should be posted in the "base" tweaker-stl repository. I didn't write the algorithm, i simply provided an interface for Cura.

As for consistency; I get the same result over and over again. It doesn't rotate them around other axis when I try it.
