### ISSUE TITLE
2.5 update

### ISSUE THREAD

**Issue by thopiekar** [nallath/CuraOrientationPlugin#9]
Is the plugin still working with 2.5?

**Comment by nallath** [comment]
It should be. Nothing major changed.

**Comment by a1xon** [comment]
Cura 2.6.2 crashes on startup while loading the plugin when CuraOrientationPlugin Folder is added to the Plugin Folder (Windows 7)

**Comment by cecilyen** [comment]
I can confirm that CuraOrientationPlugin doesn't work on Cura 2.6.2 with macOS 10.12.

**Comment by nallath** [comment]
Have a look at the 2.6 branch. The master branch is updated in order to work with the (upcoming) 2.7 changes
